packages:
  - pizzaz_server_node
  - kitchen_sink_server_node
  - cards_against_ai_server_node
  - mcp_app_basics_node
  - cad_standards_server_node

allowBuilds:
  '@modelcontextprotocol/ext-apps': true
  '@tailwindcss/oxide': true
  esbuild: true

onlyBuiltDependencies:
  - '@modelcontextprotocol/ext-apps'
  - '@tailwindcss/oxide'
  - esbuild
